### ISSUE TITLE
Failed to start Grizzly HTTP server

### ISSUE THREAD

**Issue by eschizoid** [hazelcast/hazelcast-mesos#4]
I'm getting the following error using the folowing versions:

`Mesos 0.27.1`
`Marahton 1.1.1`

```
Exception in thread "main" javax.ws.rs.ProcessingException: Failed to start Grizzly HTTP server: Cannot assign requested address
    at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:302)
    at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:119)
    at HazelcastMain.initializeHttpServer(HazelcastMain.java:41)
    at HazelcastMain.main(HazelcastMain.java:25)
Caused by: java.net.BindException: Cannot assign requested address
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:433)
    at sun.nio.ch.Net.bind(Net.java:425)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bindToChannelAndAddress(TCPNIOBindingHandler.java:132)
    at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bind(TCPNIOBindingHandler.java:88)
    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:236)
    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:216)
    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:207)
    at org.glassfish.grizzly.http.server.NetworkListener.start(NetworkListener.java:680)
    at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:278)
    at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:299)
    ... 3 more
```

**Comment by eminn** [comment]
Can you share your marathon application json and environment variables ?

**Comment by eschizoid** [comment]
@eminn Sorry for my late reply. I'm using the same configuration that the `README` file indicates. However I'm using `docker` to run  `marathon` and `mesos`. Would it be helpful tho share my `docker-compose` file?

BTW, I'm using the official mesosphere images for `marathon` and `mesos`.

**Comment by eschizoid** [comment]
@eminn any idea what the issue might be?

**Comment by eminn** [comment]
@eschizoid sorry for the late reply, I was on vacation.

The scheduler creates a web server to distribute binaries to executors and that web server tries to bind itself to `HOST:PORT`, the default value for `HOST` environment variable is `local host name` and for the  default value for `PORT` variable is `8090`.

Can you check whether any other service is running on the port `8090` ?

**Comment by eschizoid** [comment]
@eminn Confirmed, I don't have any other service running on port `8090`

**Comment by eschizoid** [comment]
Hi @eminn I upgraded to the latest version of `mesos/marathon` and now the error that I'm seeing is from one of the `mesos` slaves is the following:

```
I0812 14:50:06.079504 14859 logging.cpp:188] INFO level logging started!
I0812 14:50:06.079879 14859 fetcher.cpp:424] Fetcher Info: {"cache_directory":"\/tmp\/mesos\/fetch\/slaves\/6d1d98f0-756f-4c37-a492-41e6d819cdb4-S0\/root","items":[{"action":"BYPASS_CACHE","uri":{"cache":false,"executable":false,"extract":true,"value":"https:\/\/s3.amazonaws.com\/hazelcast\/mesos\/hazelcast-mesos-0.1.tar.gz"}}],"sandbox_directory":"\/var\/lib\/mesos\/slave\/slaves\/6d1d98f0-756f-4c37-a492-41e6d819cdb4-S0\/frameworks\/6d1d98f0-756f-4c37-a492-41e6d819cdb4-0000\/executors\/hazelcast.0eb77f21-609c-11e6-9a81-1a43a1b6df16\/runs\/1a6b3291-532b-4035-9bd7-a37bc49deb2e","user":"root"}
I0812 14:50:06.081496 14859 fetcher.cpp:379] Fetching URI 'https://s3.amazonaws.com/hazelcast/mesos/hazelcast-mesos-0.1.tar.gz'
I0812 14:50:06.081518 14859 fetcher.cpp:250] Fetching directly into the sandbox directory
I0812 14:50:06.081540 14859 fetcher.cpp:187] Fetching URI 'https://s3.amazonaws.com/hazelcast/mesos/hazelcast-mesos-0.1.tar.gz'
I0812 14:50:06.081557 14859 fetcher.cpp:134] Downloading resource from 'https://s3.amazonaws.com/hazelcast/mesos/hazelcast-mesos-0.1.tar.gz' to '/var/lib/mesos/slave/slaves/6d1d98f0-756f-4c37-a492-41e6d819cdb4-S0/frameworks/6d1d98f0-756f-4c37-a492-41e6d819cdb4-0000/executors/hazelcast.0eb77f21-609c-11e6-9a81-1a43a1b6df16/runs/1a6b3291-532b-4035-9bd7-a37bc49deb2e/hazelcast-mesos-0.1.tar.gz'
I0812 14:50:06.299124 14859 fetcher.cpp:84] Extracting with command: tar -C '/var/lib/mesos/slave/slaves/6d1d98f0-756f-4c37-a492-41e6d819cdb4-S0/frameworks/6d1d98f0-756f-4c37-a492-41e6d819cdb4-0000/executors/hazelcast.0eb77f21-609c-11e6-9a81-1a43a1b6df16/runs/1a6b3291-532b-4035-9bd7-a37bc49deb2e' -xf '/var/lib/mesos/slave/slaves/6d1d98f0-756f-4c37-a492-41e6d819cdb4-S0/frameworks/6d1d98f0-756f-4c37-a492-41e6d819cdb4-0000/executors/hazelcast.0eb77f21-609c-11e6-9a81-1a43a1b6df16/runs/1a6b3291-532b-4035-9bd7-a37bc49deb2e/hazelcast-mesos-0.1.tar.gz'
I0812 14:50:06.469746 14859 fetcher.cpp:92] Extracted '/var/lib/mesos/slave/slaves/6d1d98f0-756f-4c37-a492-41e6d819cdb4-S0/frameworks/6d1d98f0-756f-4c37-a492-41e6d819cdb4-0000/executors/hazelcast.0eb77f21-609c-11e6-9a81-1a43a1b6df16/runs/1a6b3291-532b-4035-9bd7-a37bc49deb2e/hazelcast-mesos-0.1.tar.gz' into '/var/lib/mesos/slave/slaves/6d1d98f0-756f-4c37-a492-41e6d819cdb4-S0/frameworks/6d1d98f0-756f-4c37-a492-41e6d819cdb4-0000/executors/hazelcast.0eb77f21-609c-11e6-9a81-1a43a1b6df16/runs/1a6b3291-532b-4035-9bd7-a37bc49deb2e'
I0812 14:50:06.469799 14859 fetcher.cpp:456] Fetched 'https://s3.amazonaws.com/hazelcast/mesos/hazelcast-mesos-0.1.tar.gz' to '/var/lib/mesos/slave/slaves/6d1d98f0-756f-4c37-a492-41e6d819cdb4-S0/frameworks/6d1d98f0-756f-4c37-a492-41e6d819cdb4-0000/executors/hazelcast.0eb77f21-609c-11e6-9a81-1a43a1b6df16/runs/1a6b3291-532b-4035-9bd7-a37bc49deb2e/hazelcast-mesos-0.1.tar.gz'
I0812 14:50:06.583722 14832 exec.cpp:143] Version: 0.28.1
I0812 14:50:06.586540 14869 exec.cpp:217] Executor registered on slave 6d1d98f0-756f-4c37-a492-41e6d819cdb4-S0
sh: java: command not found
```

Seems that the image doesn't java installed?

**Comment by eminn** [comment]
Hi @eschizoid ,

Yes it doesn't install Java by default. I think I need to update and add Java to pre-requisites.

**Comment by eminn** [comment]
I've just checked, it was already in the pre-requisites list. Check out https://github.com/hazelcast/hazelcast-mesos#prerequisites

**Comment by eschizoid** [comment]
Wouldn't be more easier to provision a base image that has `java` installed along with the `dist` version of `hazelcast-mesos`? I feel having to install `java` in all the different slaves defeats the whole purpose of what we are trying to accomplish with `mesos` and `marathon`.

`mesos` slaves are never provision with `java`, so every time I make a new slave I would have to make sure it has `java` installed, otherwise this is not going to work.

**Comment by eminn** [comment]
I see your point and makes sense to have it that way. Thanks for your suggestion.

**Comment by eminn** [comment]
I've created an issue for that, https://github.com/hazelcast/hazelcast-mesos/issues/5

**Comment by eschizoid** [comment]
Great closing #4
